name: Terraform Plan & Apply

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

env:
  AWS_REGION: eu-west-1

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfvars file from S3
        run: aws s3 cp s3://mahi-s3/terraform.tfvars terraform/terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: |
          find terraform -type f -name "*.tf" -exec terraform fmt -check -diff {} +


      - name: Install and Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          export PATH=$PATH:$(pwd)
          tflint --version
          tflint --init

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: terraform

      - name: Summary
        run: echo "### ✅ Terraform Plan & Apply Completed" >> $GITHUB_STEP_SUMMARY
